/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colecciones;

import javax.swing.*;
import java.util.*;

public class MiCuestionario extends javax.swing.JFrame {

    JLabel etiquetaPregunta;
    int indicePregunta = 0;
    int acierto = 0;
    List<JRadioButton> radios;
    ButtonGroup grupo;

    public MiCuestionario() {
        initComponents();
        setLocationRelativeTo(this);
        etiquetaPregunta = new JLabel();
        //Agregamos al panel la etiqueta con un texo
        etiquetaPregunta.setText(obtenerPreguntas().get(indicePregunta).getTitulo());
        panelPregunta.add(etiquetaPregunta);
        //Primero generamos el Arreglo
        radios = new ArrayList<>();
        grupo = new ButtonGroup();

        //Generamos las opciones
        for (Opcion o : obtenerPreguntas().get(indicePregunta).getOpciones()) {
            JRadioButton r = new JRadioButton();

            r.setText(o.getTitulo());
            radios.add(r);
        }
        for (JRadioButton r : radios) {
            grupo.add(r);
            panelPregunta.add(r);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPregunta = new javax.swing.JPanel();
        siguientePregunta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPregunta.setBackground(new java.awt.Color(204, 255, 204));
        panelPregunta.setLayout(new javax.swing.BoxLayout(panelPregunta, javax.swing.BoxLayout.Y_AXIS));

        siguientePregunta.setText("Siguiente >>");
        siguientePregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguientePreguntaActionPerformed(evt);
            }
        });

        jLabel1.setText("Resultado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(siguientePregunta)
                        .addGap(0, 175, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(siguientePregunta)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguientePreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguientePreguntaActionPerformed
        // TODO add your handling code here:
        //Checamos antes cual de las opciones fue seleccionada e incremento
        //aciertos en 1 , si es que coincide cn la correcta
        verificarRespuesta();

        indicePregunta++;
        panelPregunta.removeAll();
        panelPregunta.repaint();

        if (indicePregunta < obtenerPreguntas().size()) {
            panelPregunta.add(etiquetaPregunta);
            etiquetaPregunta.setText(obtenerPreguntas()
                    .get(indicePregunta).getTitulo());
            //Primero generamos el Arreglo
            radios = new ArrayList<>();
            grupo = new ButtonGroup();

            //Generamos las opciones
            for (Opcion o : obtenerPreguntas().get(indicePregunta).getOpciones()) {
                JRadioButton r = new JRadioButton();

                r.setText(o.getTitulo());
                radios.add(r);
            }
            for (JRadioButton r : radios) {
                grupo.add(r);

                panelPregunta.add(r);
            }

        }
    }//GEN-LAST:event_siguientePreguntaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiCuestionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelPregunta;
    private javax.swing.JButton siguientePregunta;
    // End of variables declaration//GEN-END:variables

    public List<Pregunta> obtenerPreguntas() {
        //Primero generamos las opciones de cada pregunta
        //Pregunta 1
        Opcion op11 = new Opcion();
        op11.setTitulo("México");
        op11.setCorrecta(false);

        Opcion op21 = new Opcion("Moscu", false);

        Opcion op31 = new Opcion();
        op31.setTitulo("El Cairo");
        op31.setCorrecta(true);

        Opcion op41 = new Opcion();
        op41.setTitulo("Mizcalco");
        op41.setCorrecta(false);

        //Opciones de la segunda pregunta
        Opcion op12 = new Opcion("Atlantico", true);
        Opcion op22 = new Opcion("Artico", false);
        Opcion op32 = new Opcion("Pacifico", true);
        Opcion op42 = new Opcion("Indico", false);
        Opcion op52 = new Opcion("Antartico", false);

        //Opciones de la tercer pregunta
        Opcion op13 = new Opcion("Falso", true);
        Opcion op23 = new Opcion("Verdadero", false);
        Pregunta p3 = new Pregunta();
        p3.setTitulo("Pasaré prog. o. a objetos?");
        List<Opcion> op3 = new ArrayList<>();
        op3.add(op13);
        op3.add(op23);
        p3.setOpciones(op3);

        //Ahora generamos las opciones para la primer pregunta
        Pregunta p1 = new Pregunta();
        p1.setTitulo("Capital de Egipto");
        //ESto es lo interesante

        List<Opcion> opcionesp1 = new ArrayList<>();
        opcionesp1.add(op11);
        opcionesp1.add(op21);
        opcionesp1.add(op31);
        opcionesp1.add(op41);
        p1.setOpciones(opcionesp1);
        //p1.setOpciones(Arrays.asList(op11,op21,op31,op41)); 
        //Para la pregunta 2
        Pregunta p2 = new Pregunta();
        p2.setTitulo("Oceanos que rodean a Oaxaca");
        p2.setOpciones(Arrays.asList(op12, op22, op32, op42, op52));

        //Agregar las preguntas al cuetionario
        Cuestionario c = new Cuestionario();
        c.setPreguntas(Arrays.asList(p1, p2, p3));

        return c.getPreguntas();
    }

    private void verificarRespuesta() {
        for (JRadioButton r : radios) {
            if (r.isSelected()) {
                for (Opcion o : obtenerPreguntas().get(indicePregunta).getOpciones()) {
                    if (o.getTitulo().equals(r.getText()) && o.isCorrecta()) {
                        acierto++;
                    }
                }
            }
        }
        jLabel1.setText("Aciertos "+acierto);
    }
}

    
