/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colecciones;

import javax.swing.*;
import java.util.*;

public class MiCuestionario extends javax.swing.JFrame {

    /**
     * Creates new form MiCuestionario
     */
    public MiCuestionario() {
        initComponents();

        Opcion op11 = new Opcion();
        op11.setTitulo("México");
        op11.setCorrecta(false);

        Opcion op21 = new Opcion("Moscu", false);

        Opcion op31 = new Opcion();
        op31.setTitulo("El Cairo");
        op31.setCorrecta(true);

        Opcion op41 = new Opcion();
        op41.setTitulo("Mizcalco");
        op41.setCorrecta(false);

        //Opciones de la segunda pregunta
        Opcion op12 = new Opcion("Atlantico", true);
        Opcion op22 = new Opcion("Artico", false);
        Opcion op32 = new Opcion("Pacifico", true);
        Opcion op42 = new Opcion("Indico", false);
        Opcion op52 = new Opcion("Antartico", false);

        //Ahora generamos las opciones para la primer pregunta
        Pregunta p1 = new Pregunta();
        p1.setTitulo("Capital de Egipto");
        //ESto es lo interesante

        List<Opcion> opcionesp1 = new ArrayList<>();
        opcionesp1.add(op11);
        opcionesp1.add(op21);
        opcionesp1.add(op31);
        opcionesp1.add(op41);
        p1.setOpciones(opcionesp1);
        //p1.setOpciones(Arrays.asList(op11,op21,op31,op41)); 
        //Para la pregunta 2
        Pregunta p2 = new Pregunta();
        p2.setTitulo("Oceanos que rodea  a Oaxaca");
        p2.setOpciones(Arrays.asList(op12, op22, op32, op42, op52));

        //Agregar las preguntas al cuetionario
        Cuestionario c = new Cuestionario();
        c.setPreguntas(Arrays.asList(p1, p2));
        // Aqui vamos a invocar al cuestionario

        System.out.println(c.getPreguntas().size());
        
        Pregunta p = c.getPreguntas().get(0);
        //Genero la etiqueta de mi pregunta
        JLabel jp = new JLabel(p.getTitulo());
        //Generamos un ArrayList de Botones de radio

        List<JRadioButton> radios = new ArrayList<>();
       

        //Mostramos la pregunta
        panelPregunta.add(jp);
        int i = 0;
        for (Opcion o : p.getOpciones()) {
            JRadioButton radio = new JRadioButton();
          
            radio.setText(o.getTitulo());
            panelPregunta.add(radio);

            radios.add(radio);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPregunta = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPregunta.setBackground(new java.awt.Color(204, 255, 204));
        panelPregunta.setLayout(new javax.swing.BoxLayout(panelPregunta, javax.swing.BoxLayout.Y_AXIS));

        jButton1.setText("Siguiente >>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiCuestionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelPregunta;
    // End of variables declaration//GEN-END:variables
}
